### ISSUE TITLE
Флаг isOptional не работает в query параметрах для EnumProperty

### ISSUE THREAD

**Issue by lazarev1609** [ivankrtv/OpenApiDoc#18]
Например: 
Есть query и requestBody, которые используют одну и ту же дто GetMaterialByIdQueryRequestDto
<img width="819" alt="image" src="https://github.com/ivankrtv/OpenApiDoc/assets/58079326/74066f1c-99b6-40ef-964b-81d7d43c33d6">

Но для query поле обязательно, а в requestBody оно опциональное, как и должно быть
<img width="1135" alt="image" src="https://github.com/ivankrtv/OpenApiDoc/assets/58079326/b1323965-51d2-4ffd-a111-d7c6c54ebfd1">

**Comment by ivankrtv** [comment]
Исправлено в рамках #19
